    swagger: "2.0"
    info:
      title: bat-api
      description: "Test for api gateway"
      version: "1.0.0"
    schemes:
      - "https"
    paths:
      "/health_check":
        get:
          description: "Get the health status"
          operationId: "health_check"
          responses:
            200:
              description: "Success."
            500:
              description: "Internal server error."
