    swagger: "2.0"
    info:
      title: bat-api
      description: "Test for api gateway"
      version: "1.0.0"
    schemes:
      - "https"
    paths:
      "/health_check":
        get:
          description: "Get the health status"
          operationId: "health_check"
          x-google-backend:
            address: https://bat-api-fgqc4ti3nq-od.a.run.app
          responses:
            200:
              description: "Success."
            500:
              description: "Internal server error."
