# openapi2-functions.yaml
swagger: '2.0'
info:
  title: coffee-api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /health_check:
    get:
      summary: Call health_check endpoint
      operationId: health_check
      x-google-backend:
        address: https://erp-api-runner-fgqc4ti3nq-od.a.run.app/health_check
      responses:
        '200':
          description: A successful response
          schema:
            type: string

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
security:
  - api_key: []

