# openapi2-functions.yaml
swagger: '2.0'
info:
  title: coffee-api
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /health_check:
    get:
      summary: Call health_check endpoint
      operationId: health_check
      x-google-backend:
        address: https://erp-api-fgqc4ti3nq-od.a.run.app/health_check
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/mspr-epsi-coffee"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "mspr-epsi-coffee"
security:
  - firebase: []

