name: Push docker image to GCP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: rust:1.66

    steps:
      - uses: actions/checkout@v3

      - name: Check syntax code
        run: cargo check
        
      - name: Test Code
        run: cargo test

  build-and-push-to-artifact-registery:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: erp_api
      IMAGE_VERSION: 1.0

    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Build Docker Image
        run: docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION
