name: Push docker image to GCP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: rust:1.66

    steps:
      - uses: actions/checkout@v3

      - name: Check syntax code
        run: cargo check
        
      - name: Test Code
        run: cargo test

  build-and-push-to-artifact-registery:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: erp_api
      IMAGE_VERSION: 1.0

    steps:
      - uses: actions/checkout@v3
      
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t eu.gcr.io/$PROJECT_ID/erp-api/$IMAGE_NAME:$IMAGE_VERSION .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: docker push eu.gcr.io/$PROJECT_ID/erp-api/$IMAGE_NAME:$IMAGE_VERSION