name: Push docker image to GCP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66

      - name: Check syntax code
        run: cargo check

      - name: Audit code
        run: cargo audit
        
      - name: Test Code
        run: cargo test

  build-and-push-to-artifact-registery:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: erp_api
      IMAGE_VERSION: 1.0

    steps:
      - uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Build Docker Image
        #run: docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION .
        run: docker build -t eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION .

      - name: Configure Docker Client
        #run: gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet
        run: gcloud auth configure-docker --quiet

      - name: Push Docker Image to Container Registry (GCR)
        #run: docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION
        run: docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$IMAGE_VERSION
