name: Push docker image to GCP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Cache dependencies
  #       id: cache-dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cargo/registry
  #           ~/.cargo/git
  #           target
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  #     - name: Install stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.67
  #         profile: minimal
  #         override: true
        
  #     - name: Run cargo test
  #       run: cargo test

  # fmt:
  #   name: Rustfmt
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: 1.67
  #         components: rustfmt
  #         override: true

  #     - name: Run fmt 
  #       run: cargo fmt --all -- --check

  # clippy:
  #   name: Clippy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         components: clippy
  #         override: true

  #     - name: Run clippy
  #       run: cargo clippy


  build-and-push-to-artifact-registery:
    #needs: [test, fmt, clippy]
    runs-on: ubuntu-latest

    env:
      REPO_NAME: erp-api
      IMAGE_NAME: erp_api
      IMAGE_URL: europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO_NAME/$IMAGE_NAME
      CLOUD_RUN_ID: erp-api-runner

    steps:
      # - uses: actions/checkout@v3
      
      # - name: Automatic Tagging of Releases
      #   id: increment-git-tag
      #   run: |
      #     bash ./scripts/git_update.sh -v patch

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # - name: Configure Docker Client
      #   run: gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet

      # - name: Build Docker Image
      #   env:
      #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      #   run: | 
      #     docker build -t $IMAGE_URL:latest .
      #     docker build -t $IMAGE_URL:$GIT_TAG .

      # - name: Push Docker Image to Container Registry (GCR)
      #   env:
      #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      #   run: |
      #     docker push $IMAGE_URL:latest
      #     docker push $IMAGE_URL:$GIT_TAG

      - name: Deploy To Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_ID --image=$IMAGE_URL:0.1.1 \
            --region=europe-west9 \
            --min-instances=0 \
            --max-instances=1 \
            --port=8000
